 [common]
  meta-join = ["opengemini-meta-01.test.svc.cluster.local:8092","opengemini-meta-02.test.svc.cluster.local:8092", "opengemini-meta-03.test.svc.cluster.local:8092"]
  executor-memory-size-limit = "16G"
  executor-memory-wait-time = "0s"
  # pprof-enabled = false
  cpu-num = 8
  memory-size = "32G"

[meta]
  bind-address = "{{addr}}:8088"
  http-bind-address = "{{addr}}:8091"
  rpc-bind-address = "{{addr}}:8092"
  dir = "/yinhe/data/openGemini/meta"
  domain = "{domain}"
  #
  # expand-shards-enable = false
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"
  cluster-tracing = true
  logging-enabled = true
  lease-duration = "1m0s"
  meta-version = 2
  split-row-threshold = 10000
  imbalance-factor = 0.3
  # auth-enabled = false
  https-enabled = false
  # ptnum-pernode = 1
  
[coordinator]
  write-timeout = "120s"
  shard-writer-timeout = "120s"
  shard-mapper-timeout = "3000m"
  max-remote-write-connections = 100
  max-remote-read-connections = 100
  shard-tier = "warm"
  rp-limit = 100
  # force-broadcast-query = false
  # time-range-limit = ["72h", "24h"]
  
[http]
  bind-address = "{{addr}}:8086"
  auth-enabled = false
  # weakpwd-path = "/tmp/openGemini/weakpasswd.properties"
  pprof-enabled = true
  max-connection-limit = 0
  max-concurrent-write-limit = 0
  max-enqueued-write-limit = 0
  enqueued-write-timeout = "10m"
  max-concurrent-query-limit = 0
  max-enqueued-query-limit = 0
  enqueued-query-timeout = "5m"
  chunk-reader-parallel = 0
  max-body-size = 0
  https-enabled = false
  
[data]
  store-ingest-addr = "{{addr}}:8400"
  store-select-addr = "{{addr}}:8401"
  store-data-dir = "/yinhe/data/openGemini"
  store-wal-dir = "/yinhe/data/openGemini"
  store-meta-dir = "/yinhe/data/openGemini/meta"
  domain = "{domain}"
  wal-enabled = true
  wal-sync-interval = "100ms"
  wal-replay-parallel = true
  imm-table-max-memory-percentage = 10
  write-cold-duration = "5s"
  shard-mutable-size-limit = "384m"
  node-mutable-size-limit = "1024m"
  max-write-hang-time = "15s"
  max-concurrent-compactions = 6
  compact-full-write-cold-duration = "1h"
  max-full-compactions = 1
  # compact-throughput = "80m"
  # compact-throughput-burst = "90m"
  # compact-recovery = false
  # snapshot-throughput = "64m"
  # snapshot-throughput-burst = "70m"
  # Whether to cache data blocks in hot shard
  cache-table-data-block = false
  # Whether to cache meta blocks in hot shard
  cache-table-meta-block = false
  # Whether to use mmap ability
  enable-mmap-read = false
  # The limit of read cache use size, The unit is byte, less than or equal to 0 is unused, recommend 5368709120 if use
  read-cache-limit = 0
  write-concurrent-limit = 0
  # open-shard-limit = 0
  readonly = false
  # downsample-write-drop = true
  mem-data-read-enabled = false
  # 防止查询OOM 
  query-series-limit = 100000
  
[data.ops-monitor]
      store-http-addr = ""
      auth-enabled = false
      store-https-enabled = false
      store-https-certificate = ""
  
[retention]
  # enabled = true
  # check-interval = "30m"
  
[downsample]
  # enable = true
  # check-interval = "30m"
  
[logging]
  format = "auto"
  level = "info"
  path = "/yinhe/logs/openGemini"
  max-size = "256m"
  max-num = 30
  max-age = 7
  compress-enabled = true
  
[tls]
  min-version = "TLS1.2"
   ciphers = [
     "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
     "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
     "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
     "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
   ]
  
[monitor]
  pushers = "http"
  store-enabled = true
  store-database = "monitor_internal"
  store-interval = "10s"
  # https-enabled = false
  # store-path = "/tmp/openGemini/metric/metric.data"
  # compress = false
  http-endpoint = "opengemini-sql-01.test.svc.cluster.local:8086"
  # username = ""
  # password = ""
  
[gossip]
  enabled = true
  log-enabled = true
  bind-address = "{{addr}}"
  store-bind-port = 8011
  meta-bind-port = 8010
  prob-interval = '1s'
  suspicion-mult = 4
  members = ["opengemini-meta-01.test.svc.cluster.local:8010", "opengemini-meta-02.test.svc.cluster.local:8010", "opengemini-meta-03.test.svc.cluster.local:8010"]
  
[spdy]
  recv-window-size = 16
  concurrent-accept-session = 4096
  open-session-timeout = "5m"
  session-select-timeout = "5m"
  # data-ack-timeout = "10s"
  tcp-dial-timeout = "10s"
  # tls-enable = false
  # tls-insecure-skip-verify = false
  # tls-client-auth = true
  # tls-certificate = ""
  # tls-private-key = ""
  # tls-server-name = ""
  # conn-pool-size = 4
  # tls-client-certificate = ""
  # tls-client-private-key = ""
  # tls-ca-root = ""
